name: Node.js CI

on:
  push:
    branches: ["master"]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.1'
          cache: 'npm'

      - name: Cache Dependencies
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm

      - name: Install Dependencies
        run: npm ci

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: npm run build --if-present

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: npm run test
